alter table if exists site_settings
  add column if not exists hero_chips jsonb not null default '[]'::jsonb,
  add column if not exists feature_cards jsonb not null default '[]'::jsonb,
  add column if not exists workflow_steps jsonb not null default '[]'::jsonb,
  add column if not exists plan_highlights jsonb not null default '[]'::jsonb;

insert into site_settings (
  id,
  site_name_vi,
  site_name_en,
  hero_eyebrow_vi,
  hero_eyebrow_en,
  hero_title_vi,
  hero_title_en,
  hero_description_vi,
  hero_description_en,
  hero_secondary_text_vi,
  hero_secondary_text_en,
  hero_primary_cta_label_vi,
  hero_primary_cta_label_en,
  hero_primary_cta_href,
  hero_secondary_cta_label_vi,
  hero_secondary_cta_label_en,
  hero_secondary_cta_href,
  hero_image_path,
  hero_image_alt_vi,
  hero_image_alt_en,
  announcement_text_vi,
  announcement_text_en,
  announcement_visible,
  show_featured_plans_section,
  show_donate_section,
  show_faq_section,
  navigation,
  footer_note_vi,
  footer_note_en,
  faq_items,
  hero_chips,
  feature_cards,
  workflow_steps,
  plan_highlights,
  updated_at
) values (
  'global',
  'Hang Cú video',
  'Hang Cú Video',
  'Cửa hàng license cho Hang Cú video',
  'License storefront for Hang Cú video',
  'Bán license phần mềm theo gói 30 ngày và trọn đời.',
  'Sell software licenses with 30-day and lifetime plans.',
  'Mua license bằng vài bước đơn giản, nhận key qua email và có gói hỗ trợ riêng nếu cần.',
  'The store supports Vietnamese and English, with auto-issued license keys and a separate optional support package.',
  'Thiết kế gọn nhẹ cho lượng đơn nhỏ mỗi tháng, nhưng vẫn sẵn sàng mở rộng khi cần.',
  'Suitable for a few dozen orders per month and easy to scale later.',
  'Xem gói license',
  'Browse license plans',
  '/products',
  'Bắt đầu checkout',
  'Start checkout',
  '/checkout',
  '/brand/hangcu-hero-imac.png',
  'Ảnh hero của Hang Cú video',
  'Hang Cú video hero image',
  'Đang mở bán license Hang Cú video.',
  'Now selling Hang Cú video licenses.',
  true,
  true,
  true,
  true,
  '[{"label":"Gói license","href":"/products","visible":true},{"label":"Bảng giá","href":"/pricing","visible":true},{"label":"Supporter packages","href":"/collections","visible":true},{"label":"Download","href":"/download","visible":true},{"label":"Thanh toán","href":"/checkout","visible":true},{"label":"Đơn hàng","href":"/orders","visible":true},{"label":"Hỗ trợ","href":"/contact","visible":true}]'::jsonb,
  'Bản storefront song ngữ cho Hang Cú video, chỉ bán license phần mềm.',
  'Bilingual storefront for Hang Cú video, selling software licenses only.',
  '[{"questionVi":"License 30 ngày là gì?","answerVi":"Đây là gói truy cập có thời hạn 30 ngày.","questionEn":"What is the 30-day license?","answerEn":"It is a time-limited access plan for 30 days.","visible":true},{"questionVi":"License trọn đời là gì?","answerVi":"Đây là gói dùng vĩnh viễn theo điều khoản sản phẩm.","questionEn":"What is the lifetime license?","answerEn":"It is permanent access under the product terms.","visible":true}]'::jsonb,
  '[{"labelVi":"Join","labelEn":"Join","visible":true},{"labelVi":"Cut","labelEn":"Cut","visible":true},{"labelVi":"Thumb / Face Find","labelEn":"Thumb / Face Find","visible":true},{"labelVi":"Watermark","labelEn":"Watermark","visible":true},{"labelVi":"Intro / Outro","labelEn":"Intro / Outro","visible":true},{"labelVi":"Optimize / Encode","labelEn":"Optimize / Encode","visible":true}]'::jsonb,
  '[{"labelVi":"Join","labelEn":"Join","textVi":"Ghép nhiều clip theo đúng thứ tự, có kéo thả để đổi thứ tự.","textEn":"Merge clips in order, with drag-and-drop reordering.","visible":true},{"labelVi":"Cut","labelEn":"Cut","textVi":"Cắt đầu video hàng loạt để trim nhanh trên nhiều file.","textEn":"Trim the head of many videos in one fast batch.","visible":true},{"labelVi":"Thumb / Face Find","labelEn":"Thumb / Face Find","textVi":"Xuất thumbnail, contact sheet, chọn frame, chia grid, chỉnh chất lượng.","textEn":"Export thumbnails and contact sheets with frame, grid, and quality controls.","visible":true},{"labelVi":"Watermark","labelEn":"Watermark","textVi":"Thêm watermark đầy đủ hoặc watermark ẩn cho video.","textEn":"Add visible or hidden watermarks to video files.","visible":true}]'::jsonb,
  '[{"stepVi":"Kéo video vào module","stepEn":"Drag files into a module","visible":true},{"stepVi":"Chọn preset / grid / chất lượng","stepEn":"Choose preset / grid / quality","visible":true},{"stepVi":"Bấm xử lý hàng loạt","stepEn":"Run batch processing","visible":true},{"stepVi":"Xuất file sạch ngay","stepEn":"Export clean output","visible":true}]'::jsonb,
  '[{"labelVi":"30 ngày","labelEn":"30 days","textVi":"Dùng ngắn hạn, test workflow, đổi máy dễ hơn","textEn":"Short-term use and workflow testing","visible":true},{"labelVi":"Trọn đời","labelEn":"Lifetime","textVi":"Một lần thanh toán, dùng lâu dài","textEn":"One-time payment, long-term use","visible":true},{"labelVi":"Support package","labelEn":"Support package","textVi":"Tách riêng, không trộn với license","textEn":"Separate from the license purchase","visible":true}]'::jsonb,
  timezone('utc', now())
) on conflict (id) do update set
  site_name_vi = excluded.site_name_vi,
  site_name_en = excluded.site_name_en,
  hero_eyebrow_vi = excluded.hero_eyebrow_vi,
  hero_eyebrow_en = excluded.hero_eyebrow_en,
  hero_title_vi = excluded.hero_title_vi,
  hero_title_en = excluded.hero_title_en,
  hero_description_vi = excluded.hero_description_vi,
  hero_description_en = excluded.hero_description_en,
  hero_secondary_text_vi = excluded.hero_secondary_text_vi,
  hero_secondary_text_en = excluded.hero_secondary_text_en,
  hero_primary_cta_label_vi = excluded.hero_primary_cta_label_vi,
  hero_primary_cta_label_en = excluded.hero_primary_cta_label_en,
  hero_primary_cta_href = excluded.hero_primary_cta_href,
  hero_secondary_cta_label_vi = excluded.hero_secondary_cta_label_vi,
  hero_secondary_cta_label_en = excluded.hero_secondary_cta_label_en,
  hero_secondary_cta_href = excluded.hero_secondary_cta_href,
  hero_image_path = excluded.hero_image_path,
  hero_image_alt_vi = excluded.hero_image_alt_vi,
  hero_image_alt_en = excluded.hero_image_alt_en,
  announcement_text_vi = excluded.announcement_text_vi,
  announcement_text_en = excluded.announcement_text_en,
  announcement_visible = excluded.announcement_visible,
  show_featured_plans_section = excluded.show_featured_plans_section,
  show_donate_section = excluded.show_donate_section,
  show_faq_section = excluded.show_faq_section,
  navigation = excluded.navigation,
  footer_note_vi = excluded.footer_note_vi,
  footer_note_en = excluded.footer_note_en,
  faq_items = excluded.faq_items,
  hero_chips = excluded.hero_chips,
  feature_cards = excluded.feature_cards,
  workflow_steps = excluded.workflow_steps,
  plan_highlights = excluded.plan_highlights,
  updated_at = excluded.updated_at;

