create table if not exists site_settings (
  id text primary key,
  site_name_vi text not null,
  site_name_en text not null,
  hero_eyebrow_vi text not null,
  hero_eyebrow_en text not null,
  hero_title_vi text not null,
  hero_title_en text not null,
  hero_description_vi text not null,
  hero_description_en text not null,
  hero_secondary_text_vi text not null,
  hero_secondary_text_en text not null,
  hero_primary_cta_label_vi text not null,
  hero_primary_cta_label_en text not null,
  hero_primary_cta_href text not null,
  hero_secondary_cta_label_vi text not null,
  hero_secondary_cta_label_en text not null,
  hero_secondary_cta_href text not null,
  hero_image_path text,
  hero_image_alt_vi text,
  hero_image_alt_en text,
  announcement_text_vi text not null,
  announcement_text_en text not null,
  announcement_visible boolean not null default true,
  show_featured_plans_section boolean not null default true,
  show_donate_section boolean not null default true,
  show_faq_section boolean not null default true,
  navigation jsonb not null default '[]'::jsonb,
  footer_note_vi text not null,
  footer_note_en text not null,
  faq_items jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default timezone('utc', now())
);

insert into site_settings (
  id,
  site_name_vi,
  site_name_en,
  hero_eyebrow_vi,
  hero_eyebrow_en,
  hero_title_vi,
  hero_title_en,
  hero_description_vi,
  hero_description_en,
  hero_secondary_text_vi,
  hero_secondary_text_en,
  hero_primary_cta_label_vi,
  hero_primary_cta_label_en,
  hero_primary_cta_href,
  hero_secondary_cta_label_vi,
  hero_secondary_cta_label_en,
  hero_secondary_cta_href,
  hero_image_path,
  hero_image_alt_vi,
  hero_image_alt_en,
  announcement_text_vi,
  announcement_text_en,
  announcement_visible,
  show_featured_plans_section,
  show_donate_section,
  show_faq_section,
  navigation,
  footer_note_vi,
  footer_note_en,
  faq_items
) values (
  'global',
  'Hang Cú video',
  'Hang Cú Video',
  'Nền tảng license cho Hang Cú video',
  'License storefront for Hang Cú video',
  'Bán license phần mềm theo gói 30 ngày và trọn đời.',
  'Sell software licenses with 30-day and lifetime plans.',
  'Cửa hàng hỗ trợ tiếng Việt và tiếng Anh, kèm donate package và mã license tặng thêm.',
  'The store supports Vietnamese and English, with donate packages and bonus license keys.',
  'Phù hợp cho vài chục đơn mỗi tháng và có thể mở rộng dần.',
  'Suitable for a few dozen orders per month and easy to scale later.',
  'Xem gói license',
  'Browse license plans',
  '/products',
  'Bắt đầu checkout',
  'Start checkout',
  '/checkout',
  null,
  null,
  null,
  'Đang mở bán license Hang Cú video.',
  'Now selling Hang Cú video licenses.',
  true,
  true,
  true,
  true,
  '[{"label":"Plans","href":"/products","visible":true},{"label":"Collections","href":"/collections","visible":true},{"label":"Checkout","href":"/checkout","visible":true},{"label":"Orders","href":"/orders","visible":true},{"label":"Admin","href":"/admin","visible":true}]'::jsonb,
  'Bản storefront song ngữ cho Hang Cú video.',
  'Bilingual storefront for Hang Cú video.',
  '[{"questionVi":"License 30 ngày là gì?","answerVi":"Đây là gói truy cập có thời hạn 30 ngày.","questionEn":"What is the 30-day license?","answerEn":"It is a time-limited access plan for 30 days.","visible":true},{"questionVi":"License trọn đời là gì?","answerVi":"Đây là gói dùng vĩnh viễn theo điều khoản sản phẩm.","questionEn":"What is the lifetime license?","answerEn":"It is permanent access under the product terms.","visible":true}]'::jsonb
) on conflict (id) do nothing;
